version: "3"

volumes:
  postgres_data:
  redis-data:
  
services:
  solr:
    image: solr:7.7.2
    container_name: solr
    entrypoint:
    - bash
    - "-c"
    - "precreate-core sdmx-facet-search; exec solr -f"
    ports:
      - 8983:8983
  
  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  
  postgres:
    image: postgres:12.0
    container_name: postgres
    restart: always    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  keycloak:
    image: jboss/keycloak:7.0.0
    container_name: keycloak
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres

  config: 
    container_name: config
    build:
      context: ./dotstatsuite-config
      dockerfile: Dockerfile.dev
    ports:
      - 5007:80

  data-lifecycle-manager:
    image: siscc/dotstatsuite-data-lifecycle-manager:latest
    container_name: data-lifecycle-manager-test
    ports:
      - 7000:7002
    environment:
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      CONFIG_URL: ${CONFIG_URL}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      TRANSFER_SERVER_URL: ${TRANSFER_SERVER_URL}

  data-explorer:
    image: siscc/dotstatsuite-data-explorer:latest
    container_name: data-explorer
    ports:
      - 7005:80
    environment:
      CONFIG_URL: ${CONFIG_URL}

  share:
    image: siscc/dotstatsuite-share
    container_name: share
    ports:
      - 3007:3007
    environment: 
      SERVER_PORT: 3007
      CONFIG_URL: ${CONFIG_URL}
      SFS_URL: ${SFS_URL}
      REDIS_HOST: redis

  data-viewer:
    image: siscc/dotstatsuite-data-viewer
    container_name: data-viewer
    ports:
      - 5000:7002
    environment:
      SERVER_PORT: 7002
      CONFIG_URL: ${CONFIG_URL}

  sdmx-faceted-search:
    image: siscc/dotstatsuite-sdmx-faceted-search:latest
    container_name: sdmx-faceted-search
    ports:
      - 3004:80
    depends_on:
      - solr
    environment:
      SERVER_PORT: 80
      SERVER_HOST: ${HOST}
      CONFIG_URL: ${CONFIG_URL}
      REDIS_HOST: redis
      SOLR_HOST: solr
    entrypoint:
      - sh
      - -c
      - "sleep 30s; yarn dist:run"