version: "3"

volumes:
  mongo-data:
  solr-data:

services:
  solr:
    image: solr:9.6
    container_name: solr
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - --cloud
      - -Dsolr.modules=analysis-extras
    networks:
      - loop_network
    volumes:
      - solr-data:/var/solr

  mongo:
    image: mongo:7.0.1
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb
    networks:
      - loop_network

  config:
    image: siscc/dotstatsuite-config:develop
    container_name: config
    ports:
      - "5007:80"
    volumes:
      - "./config/assets:/opt/assets"
      - "./config/configs:/opt/configs"
      - "./config/i18n:/opt/i18n"
    environment:
      - BUCKET_PROVIDER=fs
      - DATA_DIR=/opt/
    networks:
      - loop_network

  sfs:
    image: siscc/dotstatsuite-sdmx-faceted-search:develop
    container_name: sfs
    ports:
      - ${SFS_PORT}:80
    restart: always
    networks:
      - loop_network
    environment:
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      CONFIG_URL: ${CONFIG_URL}
      MONGODB_URL: mongodb://mongo:${MONGO_PORT}
      MONGODB_DATABASE: sfs
      SOLR_HOST: solr
      SOLR_PORT: ${SOLR_PORT}
      API_KEY: ${API_KEY_SFS}

networks:
  loop_network:
    name: loop_hole_network