volumes:
  solr-data:
  mongo-data:

services:
  solr:
    image: solr:9.6
    container_name: solr
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
      - -Dsolr.modules=analysis-extras
      - -Dsolr.max.booleanClauses=4096
    networks:
      - dotstat_network
    volumes:
      - solr-data:/var/solr

  mongo:
    image: mongo:7.0.1
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb
    networks:
      - dotstat_network

  config:
    image: siscc/dotstatsuite-config:${JS_RELEASE_TAG}
    container_name: config
    ports:
      - "5007:80"
    volumes:
      - "./config/assets:/opt/assets"
      - "./config/configs:/opt/configs"
      - "./config/i18n:/opt/i18n"
    environment:
      - BUCKET_PROVIDER=fs
      - DATA_DIR=/opt/
    networks:
      - dotstat_network

  url-shortener:
    image: siscc/dotstatsuite-url-shortener:${JS_RELEASE_TAG}
    container_name: url-shortener
    ports:
      - "${SUS_PORT}:80"
    environment:
      MONGODB_URL: "mongodb://mongo:${MONGO_PORT}"
      MONGODB_DATABASE: "url-shortener"
    networks:
      - dotstat_network

  data-lifecycle-manager:
    image: siscc/dotstatsuite-data-lifecycle-manager:${JS_RELEASE_TAG}
    container_name: data-lifecycle-manager
    ports:
      - "${DLM_PORT}:7002"
    environment:
      ROBOTS_POLICY: ${ROBOTS_POLICY_DLM}
      CONFIG_URL: http://config
      TRANSFER_SERVER_URL: "${PROTOCOL}://${HOST}:${TRANSFER_PORT}/${TRANSFER_API_VERSION}"
      AUTHZ_SERVER_URL: "${PROTOCOL}://${HOST}:${AUTH_PORT}/${AUTHZ_API_VERSION}"
      SFS_URL: "http://sfs/admin"
      SFS_API_KEY: ${API_KEY_SFS}
    volumes:
      - "./config/assets:/opt/build/assets"
    networks:
      - dotstat_network

  data-explorer:
    image: siscc/dotstatsuite-data-explorer:${JS_RELEASE_TAG}
    container_name: data-explorer
    ports:
      - "${DE_PORT}:80"
    environment:
      CONFIG_URL: http://config
      AUTH_PROVIDER: ${AUTH_PROVIDER}
      GA_TOKEN: ${GA_TOKEN}
      GTM_TOKEN: ${GTM_TOKEN_DE}
      ROBOTS_POLICY: ${ROBOTS_POLICY_DE}
      SMTP_host: ${SMTP_HOST}
      SMTP_port: ${SMTP_PORT}
      SMTP_secure: ${SMTP_TLS}
      SMTP_auth_user: ${SMTP_USER}
      SMTP_auth_pass: ${SMTP_PASSWORD}
      MAIL_FROM: ${CONTACT_FROM}
      MAIL_TO: ${CONTACT_TO}
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
      SITE_ENV: ${SITE_ENV}
      SUS_URL: "http://url-shortener"
      SITE_URL: "${PROTOCOL}://localhost:${DE_PORT}"

    volumes:
      - "./config/assets:/opt/build/assets"
    networks:
      - dotstat_network

  share:
    image: siscc/dotstatsuite-share:${JS_RELEASE_TAG}
    container_name: share
    ports:
      - "${SHARE_PORT}:3007"
    environment:
      CONFIG_URL: http://config
      SITE_URL: "${PROTOCOL}://${HOST}:${DE_PORT}/share"
      MONGODB_URL: "mongodb://mongo:${MONGO_PORT}"
      MONGODB_DATABASE: "share"
      SMTP_host: ${SMTP_HOST}
      SMTP_port: ${SMTP_PORT}
      SMTP_secure: ${SMTP_TLS}
      SMTP_auth_user: ${SMTP_USER}
      SMTP_auth_pass: ${SMTP_PASSWORD}
      MAIL_FROM: ${SHARE_MAIL_FROM}
      API_KEY: ${API_KEY_SHARE}
      SECRET_KEY: ${SECRET_KEY_SHARE}
    networks:
      - dotstat_network

  data-viewer:
    image: siscc/dotstatsuite-data-viewer:${JS_RELEASE_TAG}
    container_name: data-viewer
    ports:
      - "${VIEWER_PORT}:80"
    environment:
      CONFIG_URL: http://config
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      GA_TOKEN: ${GA_TOKEN}
      GTM_TOKEN: ${GTM_TOKEN_DV}
      ROBOTS_POLICY: ${ROBOTS_POLICY_DV}
      SITE_ENV: ${SITE_ENV}
    volumes:
      - "./config/assets:/opt/build/assets"
    networks:
      - dotstat_network

  sfs:
    image: siscc/dotstatsuite-sdmx-faceted-search:${JS_RELEASE_TAG}
    container_name: sfs
    ports:
      - "${SFS_PORT}:80"
    restart: always
    environment:
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      CONFIG_URL: http://config
      MONGODB_URL: mongodb://mongo:${MONGO_PORT}
      MONGODB_DATABASE: "sfs"
      SOLR_HOST: solr
      SOLR_PORT: ${SOLR_PORT}
      API_KEY: ${API_KEY_SFS}
    networks:
      - dotstat_network

networks:
  dotstat_network:
    name: dotstat_common_network